project_id = "wxmvlrxbbdtqcjsfpwxt"

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-checkout]
verify_jwt = false

[functions.mercadopago-payment-status]
verify_jwt = false

[functions.affiliate-click]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.webhook-dispatch]
verify_jwt = false

[functions.notification-dispatch]
verify_jwt = false
