/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminBanimentosRouteImport } from './routes/admin.banimentos'
import { Route as AdminComunicadosRouteImport } from './routes/admin.comunicados'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminModeracaoRouteImport } from './routes/admin.moderacao'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAfiliadosRouteImport } from './routes/app.afiliados'
import { Route as AppApiRouteImport } from './routes/app.api'
import { Route as AppChargebacksRouteImport } from './routes/app.chargebacks'
import { Route as AppCheckoutsRouteImport } from './routes/app.checkouts'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppComissoesRouteImport } from './routes/app.comissoes'
import { Route as AppEstornosRouteImport } from './routes/app.estornos'
import { Route as AppExtratoRouteImport } from './routes/app.extrato'
import { Route as AppLinksRouteImport } from './routes/app.links'
import { Route as AppLinksDePagamentoRouteImport } from './routes/app.links-de-pagamento'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppProdutosRouteImport } from './routes/app.produtos'
import { Route as AppRepassesRouteImport } from './routes/app.repasses'
import { Route as AppSaldoRouteImport } from './routes/app.saldo'
import { Route as AppSaquesRouteImport } from './routes/app.saques'
import { Route as AppSplitRouteImport } from './routes/app.split'
import { Route as AppTaxasRouteImport } from './routes/app.taxas'
import { Route as AppTransacoesRouteImport } from './routes/app.transacoes'
import { Route as AppVendasRouteImport } from './routes/app.vendas'
import { Route as AppWebhooksRouteImport } from './routes/app.webhooks'
import { Route as AppConfiguracoesContaRouteImport } from './routes/app.configuracoes.conta'
import { Route as AppConfiguracoesEmpresaRouteImport } from './routes/app.configuracoes.empresa'
import { Route as AppConfiguracoesEquipeRouteImport } from './routes/app.configuracoes.equipe'
import { Route as AppConfiguracoesIntegracoesRouteImport } from './routes/app.configuracoes.integracoes'
import { Route as AppConfiguracoesPermissoesRouteImport } from './routes/app.configuracoes.permissoes'
import { Route as AppConfiguracoesSegurancaRouteImport } from './routes/app.configuracoes.seguranca'
import { Route as AppRelatoriosAfiliadosRouteImport } from './routes/app.relatorios.afiliados'
import { Route as AppRelatoriosFinanceiroRouteImport } from './routes/app.relatorios.financeiro'
import { Route as AppRelatoriosProdutosRouteImport } from './routes/app.relatorios.produtos'
import { Route as AppRelatoriosVendasRouteImport } from './routes/app.relatorios.vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBanimentosRoute = AdminBanimentosRouteImport.update({
  id: '/banimentos',
  path: '/banimentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComunicadosRoute = AdminComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModeracaoRoute = AdminModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAfiliadosRoute = AppAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AppRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRoute,
} as any)
const AppChargebacksRoute = AppChargebacksRouteImport.update({
  id: '/chargebacks',
  path: '/chargebacks',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutsRoute = AppCheckoutsRouteImport.update({
  id: '/checkouts',
  path: '/checkouts',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppComissoesRoute = AppComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEstornosRoute = AppEstornosRouteImport.update({
  id: '/estornos',
  path: '/estornos',
  getParentRoute: () => AppRoute,
} as any)
const AppExtratoRoute = AppExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppRoute,
} as any)
const AppLinksRoute = AppLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppRoute,
} as any)
const AppLinksDePagamentoRoute = AppLinksDePagamentoRouteImport.update({
  id: '/links-de-pagamento',
  path: '/links-de-pagamento',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppRepassesRoute = AppRepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => AppRoute,
} as any)
const AppSaldoRoute = AppSaldoRouteImport.update({
  id: '/saldo',
  path: '/saldo',
  getParentRoute: () => AppRoute,
} as any)
const AppSaquesRoute = AppSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => AppRoute,
} as any)
const AppSplitRoute = AppSplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxasRoute = AppTaxasRouteImport.update({
  id: '/taxas',
  path: '/taxas',
  getParentRoute: () => AppRoute,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesContaRoute = AppConfiguracoesContaRouteImport.update({
  id: '/configuracoes/conta',
  path: '/configuracoes/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesEmpresaRoute = AppConfiguracoesEmpresaRouteImport.update({
  id: '/configuracoes/empresa',
  path: '/configuracoes/empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesEquipeRoute = AppConfiguracoesEquipeRouteImport.update({
  id: '/configuracoes/equipe',
  path: '/configuracoes/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesIntegracoesRoute =
  AppConfiguracoesIntegracoesRouteImport.update({
    id: '/configuracoes/integracoes',
    path: '/configuracoes/integracoes',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesPermissoesRoute =
  AppConfiguracoesPermissoesRouteImport.update({
    id: '/configuracoes/permissoes',
    path: '/configuracoes/permissoes',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesSegurancaRoute =
  AppConfiguracoesSegurancaRouteImport.update({
    id: '/configuracoes/seguranca',
    path: '/configuracoes/seguranca',
    getParentRoute: () => AppRoute,
  } as any)
const AppRelatoriosAfiliadosRoute = AppRelatoriosAfiliadosRouteImport.update({
  id: '/relatorios/afiliados',
  path: '/relatorios/afiliados',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosFinanceiroRoute = AppRelatoriosFinanceiroRouteImport.update({
  id: '/relatorios/financeiro',
  path: '/relatorios/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosProdutosRoute = AppRelatoriosProdutosRouteImport.update({
  id: '/relatorios/produtos',
  path: '/relatorios/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosVendasRoute = AppRelatoriosVendasRouteImport.update({
  id: '/relatorios/vendas',
  path: '/relatorios/vendas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/banimentos': typeof AdminBanimentosRoute
  '/admin/comunicados': typeof AdminComunicadosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/afiliados': typeof AppAfiliadosRoute
  '/app/api': typeof AppApiRoute
  '/app/chargebacks': typeof AppChargebacksRoute
  '/app/checkouts': typeof AppCheckoutsRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/estornos': typeof AppEstornosRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/links': typeof AppLinksRoute
  '/app/links-de-pagamento': typeof AppLinksDePagamentoRoute
  '/app/logs': typeof AppLogsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/repasses': typeof AppRepassesRoute
  '/app/saldo': typeof AppSaldoRoute
  '/app/saques': typeof AppSaquesRoute
  '/app/split': typeof AppSplitRoute
  '/app/taxas': typeof AppTaxasRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/configuracoes/conta': typeof AppConfiguracoesContaRoute
  '/app/configuracoes/empresa': typeof AppConfiguracoesEmpresaRoute
  '/app/configuracoes/equipe': typeof AppConfiguracoesEquipeRoute
  '/app/configuracoes/integracoes': typeof AppConfiguracoesIntegracoesRoute
  '/app/configuracoes/permissoes': typeof AppConfiguracoesPermissoesRoute
  '/app/configuracoes/seguranca': typeof AppConfiguracoesSegurancaRoute
  '/app/relatorios/afiliados': typeof AppRelatoriosAfiliadosRoute
  '/app/relatorios/financeiro': typeof AppRelatoriosFinanceiroRoute
  '/app/relatorios/produtos': typeof AppRelatoriosProdutosRoute
  '/app/relatorios/vendas': typeof AppRelatoriosVendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/banimentos': typeof AdminBanimentosRoute
  '/admin/comunicados': typeof AdminComunicadosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/afiliados': typeof AppAfiliadosRoute
  '/app/api': typeof AppApiRoute
  '/app/chargebacks': typeof AppChargebacksRoute
  '/app/checkouts': typeof AppCheckoutsRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/estornos': typeof AppEstornosRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/links': typeof AppLinksRoute
  '/app/links-de-pagamento': typeof AppLinksDePagamentoRoute
  '/app/logs': typeof AppLogsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/repasses': typeof AppRepassesRoute
  '/app/saldo': typeof AppSaldoRoute
  '/app/saques': typeof AppSaquesRoute
  '/app/split': typeof AppSplitRoute
  '/app/taxas': typeof AppTaxasRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/configuracoes/conta': typeof AppConfiguracoesContaRoute
  '/app/configuracoes/empresa': typeof AppConfiguracoesEmpresaRoute
  '/app/configuracoes/equipe': typeof AppConfiguracoesEquipeRoute
  '/app/configuracoes/integracoes': typeof AppConfiguracoesIntegracoesRoute
  '/app/configuracoes/permissoes': typeof AppConfiguracoesPermissoesRoute
  '/app/configuracoes/seguranca': typeof AppConfiguracoesSegurancaRoute
  '/app/relatorios/afiliados': typeof AppRelatoriosAfiliadosRoute
  '/app/relatorios/financeiro': typeof AppRelatoriosFinanceiroRoute
  '/app/relatorios/produtos': typeof AppRelatoriosProdutosRoute
  '/app/relatorios/vendas': typeof AppRelatoriosVendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/banimentos': typeof AdminBanimentosRoute
  '/admin/comunicados': typeof AdminComunicadosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/afiliados': typeof AppAfiliadosRoute
  '/app/api': typeof AppApiRoute
  '/app/chargebacks': typeof AppChargebacksRoute
  '/app/checkouts': typeof AppCheckoutsRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comissoes': typeof AppComissoesRoute
  '/app/estornos': typeof AppEstornosRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/links': typeof AppLinksRoute
  '/app/links-de-pagamento': typeof AppLinksDePagamentoRoute
  '/app/logs': typeof AppLogsRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/repasses': typeof AppRepassesRoute
  '/app/saldo': typeof AppSaldoRoute
  '/app/saques': typeof AppSaquesRoute
  '/app/split': typeof AppSplitRoute
  '/app/taxas': typeof AppTaxasRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/webhooks': typeof AppWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/configuracoes/conta': typeof AppConfiguracoesContaRoute
  '/app/configuracoes/empresa': typeof AppConfiguracoesEmpresaRoute
  '/app/configuracoes/equipe': typeof AppConfiguracoesEquipeRoute
  '/app/configuracoes/integracoes': typeof AppConfiguracoesIntegracoesRoute
  '/app/configuracoes/permissoes': typeof AppConfiguracoesPermissoesRoute
  '/app/configuracoes/seguranca': typeof AppConfiguracoesSegurancaRoute
  '/app/relatorios/afiliados': typeof AppRelatoriosAfiliadosRoute
  '/app/relatorios/financeiro': typeof AppRelatoriosFinanceiroRoute
  '/app/relatorios/produtos': typeof AppRelatoriosProdutosRoute
  '/app/relatorios/vendas': typeof AppRelatoriosVendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/auditoria'
    | '/admin/banimentos'
    | '/admin/comunicados'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/moderacao'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/afiliados'
    | '/app/api'
    | '/app/chargebacks'
    | '/app/checkouts'
    | '/app/clientes'
    | '/app/comissoes'
    | '/app/estornos'
    | '/app/extrato'
    | '/app/links'
    | '/app/links-de-pagamento'
    | '/app/logs'
    | '/app/marketplace'
    | '/app/produtos'
    | '/app/repasses'
    | '/app/saldo'
    | '/app/saques'
    | '/app/split'
    | '/app/taxas'
    | '/app/transacoes'
    | '/app/vendas'
    | '/app/webhooks'
    | '/admin/'
    | '/app/'
    | '/app/configuracoes/conta'
    | '/app/configuracoes/empresa'
    | '/app/configuracoes/equipe'
    | '/app/configuracoes/integracoes'
    | '/app/configuracoes/permissoes'
    | '/app/configuracoes/seguranca'
    | '/app/relatorios/afiliados'
    | '/app/relatorios/financeiro'
    | '/app/relatorios/produtos'
    | '/app/relatorios/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/auditoria'
    | '/admin/banimentos'
    | '/admin/comunicados'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/moderacao'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/afiliados'
    | '/app/api'
    | '/app/chargebacks'
    | '/app/checkouts'
    | '/app/clientes'
    | '/app/comissoes'
    | '/app/estornos'
    | '/app/extrato'
    | '/app/links'
    | '/app/links-de-pagamento'
    | '/app/logs'
    | '/app/marketplace'
    | '/app/produtos'
    | '/app/repasses'
    | '/app/saldo'
    | '/app/saques'
    | '/app/split'
    | '/app/taxas'
    | '/app/transacoes'
    | '/app/vendas'
    | '/app/webhooks'
    | '/admin'
    | '/app'
    | '/app/configuracoes/conta'
    | '/app/configuracoes/empresa'
    | '/app/configuracoes/equipe'
    | '/app/configuracoes/integracoes'
    | '/app/configuracoes/permissoes'
    | '/app/configuracoes/seguranca'
    | '/app/relatorios/afiliados'
    | '/app/relatorios/financeiro'
    | '/app/relatorios/produtos'
    | '/app/relatorios/vendas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/auditoria'
    | '/admin/banimentos'
    | '/admin/comunicados'
    | '/admin/configuracoes'
    | '/admin/empresas'
    | '/admin/moderacao'
    | '/admin/suporte'
    | '/admin/usuarios'
    | '/app/afiliados'
    | '/app/api'
    | '/app/chargebacks'
    | '/app/checkouts'
    | '/app/clientes'
    | '/app/comissoes'
    | '/app/estornos'
    | '/app/extrato'
    | '/app/links'
    | '/app/links-de-pagamento'
    | '/app/logs'
    | '/app/marketplace'
    | '/app/produtos'
    | '/app/repasses'
    | '/app/saldo'
    | '/app/saques'
    | '/app/split'
    | '/app/taxas'
    | '/app/transacoes'
    | '/app/vendas'
    | '/app/webhooks'
    | '/admin/'
    | '/app/'
    | '/app/configuracoes/conta'
    | '/app/configuracoes/empresa'
    | '/app/configuracoes/equipe'
    | '/app/configuracoes/integracoes'
    | '/app/configuracoes/permissoes'
    | '/app/configuracoes/seguranca'
    | '/app/relatorios/afiliados'
    | '/app/relatorios/financeiro'
    | '/app/relatorios/produtos'
    | '/app/relatorios/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banimentos': {
      id: '/admin/banimentos'
      path: '/banimentos'
      fullPath: '/admin/banimentos'
      preLoaderRoute: typeof AdminBanimentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comunicados': {
      id: '/admin/comunicados'
      path: '/comunicados'
      fullPath: '/admin/comunicados'
      preLoaderRoute: typeof AdminComunicadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderacao': {
      id: '/admin/moderacao'
      path: '/moderacao'
      fullPath: '/admin/moderacao'
      preLoaderRoute: typeof AdminModeracaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/afiliados': {
      id: '/app/afiliados'
      path: '/afiliados'
      fullPath: '/app/afiliados'
      preLoaderRoute: typeof AppAfiliadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api': {
      id: '/app/api'
      path: '/api'
      fullPath: '/app/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chargebacks': {
      id: '/app/chargebacks'
      path: '/chargebacks'
      fullPath: '/app/chargebacks'
      preLoaderRoute: typeof AppChargebacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkouts': {
      id: '/app/checkouts'
      path: '/checkouts'
      fullPath: '/app/checkouts'
      preLoaderRoute: typeof AppCheckoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comissoes': {
      id: '/app/comissoes'
      path: '/comissoes'
      fullPath: '/app/comissoes'
      preLoaderRoute: typeof AppComissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estornos': {
      id: '/app/estornos'
      path: '/estornos'
      fullPath: '/app/estornos'
      preLoaderRoute: typeof AppEstornosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/extrato': {
      id: '/app/extrato'
      path: '/extrato'
      fullPath: '/app/extrato'
      preLoaderRoute: typeof AppExtratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/links': {
      id: '/app/links'
      path: '/links'
      fullPath: '/app/links'
      preLoaderRoute: typeof AppLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/links-de-pagamento': {
      id: '/app/links-de-pagamento'
      path: '/links-de-pagamento'
      fullPath: '/app/links-de-pagamento'
      preLoaderRoute: typeof AppLinksDePagamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtos': {
      id: '/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/repasses': {
      id: '/app/repasses'
      path: '/repasses'
      fullPath: '/app/repasses'
      preLoaderRoute: typeof AppRepassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saldo': {
      id: '/app/saldo'
      path: '/saldo'
      fullPath: '/app/saldo'
      preLoaderRoute: typeof AppSaldoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saques': {
      id: '/app/saques'
      path: '/saques'
      fullPath: '/app/saques'
      preLoaderRoute: typeof AppSaquesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/split': {
      id: '/app/split'
      path: '/split'
      fullPath: '/app/split'
      preLoaderRoute: typeof AppSplitRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taxas': {
      id: '/app/taxas'
      path: '/taxas'
      fullPath: '/app/taxas'
      preLoaderRoute: typeof AppTaxasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transacoes': {
      id: '/app/transacoes'
      path: '/transacoes'
      fullPath: '/app/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webhooks': {
      id: '/app/webhooks'
      path: '/webhooks'
      fullPath: '/app/webhooks'
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/conta': {
      id: '/app/configuracoes/conta'
      path: '/configuracoes/conta'
      fullPath: '/app/configuracoes/conta'
      preLoaderRoute: typeof AppConfiguracoesContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/empresa': {
      id: '/app/configuracoes/empresa'
      path: '/configuracoes/empresa'
      fullPath: '/app/configuracoes/empresa'
      preLoaderRoute: typeof AppConfiguracoesEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/equipe': {
      id: '/app/configuracoes/equipe'
      path: '/configuracoes/equipe'
      fullPath: '/app/configuracoes/equipe'
      preLoaderRoute: typeof AppConfiguracoesEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/integracoes': {
      id: '/app/configuracoes/integracoes'
      path: '/configuracoes/integracoes'
      fullPath: '/app/configuracoes/integracoes'
      preLoaderRoute: typeof AppConfiguracoesIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/permissoes': {
      id: '/app/configuracoes/permissoes'
      path: '/configuracoes/permissoes'
      fullPath: '/app/configuracoes/permissoes'
      preLoaderRoute: typeof AppConfiguracoesPermissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/seguranca': {
      id: '/app/configuracoes/seguranca'
      path: '/configuracoes/seguranca'
      fullPath: '/app/configuracoes/seguranca'
      preLoaderRoute: typeof AppConfiguracoesSegurancaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios/afiliados': {
      id: '/app/relatorios/afiliados'
      path: '/relatorios/afiliados'
      fullPath: '/app/relatorios/afiliados'
      preLoaderRoute: typeof AppRelatoriosAfiliadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios/financeiro': {
      id: '/app/relatorios/financeiro'
      path: '/relatorios/financeiro'
      fullPath: '/app/relatorios/financeiro'
      preLoaderRoute: typeof AppRelatoriosFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios/produtos': {
      id: '/app/relatorios/produtos'
      path: '/relatorios/produtos'
      fullPath: '/app/relatorios/produtos'
      preLoaderRoute: typeof AppRelatoriosProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios/vendas': {
      id: '/app/relatorios/vendas'
      path: '/relatorios/vendas'
      fullPath: '/app/relatorios/vendas'
      preLoaderRoute: typeof AppRelatoriosVendasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminBanimentosRoute: typeof AdminBanimentosRoute
  AdminComunicadosRoute: typeof AdminComunicadosRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminModeracaoRoute: typeof AdminModeracaoRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminBanimentosRoute: AdminBanimentosRoute,
  AdminComunicadosRoute: AdminComunicadosRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminModeracaoRoute: AdminModeracaoRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAfiliadosRoute: typeof AppAfiliadosRoute
  AppApiRoute: typeof AppApiRoute
  AppChargebacksRoute: typeof AppChargebacksRoute
  AppCheckoutsRoute: typeof AppCheckoutsRoute
  AppClientesRoute: typeof AppClientesRoute
  AppComissoesRoute: typeof AppComissoesRoute
  AppEstornosRoute: typeof AppEstornosRoute
  AppExtratoRoute: typeof AppExtratoRoute
  AppLinksRoute: typeof AppLinksRoute
  AppLinksDePagamentoRoute: typeof AppLinksDePagamentoRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRepassesRoute: typeof AppRepassesRoute
  AppSaldoRoute: typeof AppSaldoRoute
  AppSaquesRoute: typeof AppSaquesRoute
  AppSplitRoute: typeof AppSplitRoute
  AppTaxasRoute: typeof AppTaxasRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
  AppVendasRoute: typeof AppVendasRoute
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConfiguracoesContaRoute: typeof AppConfiguracoesContaRoute
  AppConfiguracoesEmpresaRoute: typeof AppConfiguracoesEmpresaRoute
  AppConfiguracoesEquipeRoute: typeof AppConfiguracoesEquipeRoute
  AppConfiguracoesIntegracoesRoute: typeof AppConfiguracoesIntegracoesRoute
  AppConfiguracoesPermissoesRoute: typeof AppConfiguracoesPermissoesRoute
  AppConfiguracoesSegurancaRoute: typeof AppConfiguracoesSegurancaRoute
  AppRelatoriosAfiliadosRoute: typeof AppRelatoriosAfiliadosRoute
  AppRelatoriosFinanceiroRoute: typeof AppRelatoriosFinanceiroRoute
  AppRelatoriosProdutosRoute: typeof AppRelatoriosProdutosRoute
  AppRelatoriosVendasRoute: typeof AppRelatoriosVendasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAfiliadosRoute: AppAfiliadosRoute,
  AppApiRoute: AppApiRoute,
  AppChargebacksRoute: AppChargebacksRoute,
  AppCheckoutsRoute: AppCheckoutsRoute,
  AppClientesRoute: AppClientesRoute,
  AppComissoesRoute: AppComissoesRoute,
  AppEstornosRoute: AppEstornosRoute,
  AppExtratoRoute: AppExtratoRoute,
  AppLinksRoute: AppLinksRoute,
  AppLinksDePagamentoRoute: AppLinksDePagamentoRoute,
  AppLogsRoute: AppLogsRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRepassesRoute: AppRepassesRoute,
  AppSaldoRoute: AppSaldoRoute,
  AppSaquesRoute: AppSaquesRoute,
  AppSplitRoute: AppSplitRoute,
  AppTaxasRoute: AppTaxasRoute,
  AppTransacoesRoute: AppTransacoesRoute,
  AppVendasRoute: AppVendasRoute,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
  AppConfiguracoesContaRoute: AppConfiguracoesContaRoute,
  AppConfiguracoesEmpresaRoute: AppConfiguracoesEmpresaRoute,
  AppConfiguracoesEquipeRoute: AppConfiguracoesEquipeRoute,
  AppConfiguracoesIntegracoesRoute: AppConfiguracoesIntegracoesRoute,
  AppConfiguracoesPermissoesRoute: AppConfiguracoesPermissoesRoute,
  AppConfiguracoesSegurancaRoute: AppConfiguracoesSegurancaRoute,
  AppRelatoriosAfiliadosRoute: AppRelatoriosAfiliadosRoute,
  AppRelatoriosFinanceiroRoute: AppRelatoriosFinanceiroRoute,
  AppRelatoriosProdutosRoute: AppRelatoriosProdutosRoute,
  AppRelatoriosVendasRoute: AppRelatoriosVendasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
